### ISSUE TITLE
Field "Show until" not working with the sibling navigation - News is still callable over the navigation, if enddate is already reached

### ISSUE THREAD

**Issue by martin-netprofit** [1up-lab/contao-sibling-navigation#16]
Hello, 
the field "Show until" is not working with the sibling navigation. 
If a news has an "show until"-date and this is allready reached, the news ist still callable in the navgiation-template and  a 404 page becomes visible.

Contao: 4.9.20
Modul-Version: 1.2.0

**Comment by bytehead** [comment]
Correct, it only respects the `publish` field so far.

**Comment by martin-netprofit** [comment]
Wow, that was fast 😅
Can i fix this on my own in the template maybe or could this be changed in the future?

**Comment by bytehead** [comment]
You can't fix this in a template. It's the database query that has to be adjusted. I'll provide a fix for it.

**Comment by martin-netprofit** [comment]
Thank you 😊

**Comment by bytehead** [comment]
Can you check/test/require the branch `dev-fix/start-stop-times` instead of `^1.2`?

**Comment by bytehead** [comment]
@martin-netprofit could you already check, if the branch fixes your issue?

**Comment by martin-netprofit** [comment]
Hello bytehead,

no, unfortunately it still doesn't work for me

![Bildschirmfoto 2021-11-02 um 11 30 27](https://user-images.githubusercontent.com/25613502/139830516-61d8e201-0d50-46f6-8847-87cc97fed8d4.jpg)

**Comment by bytehead** [comment]
But you could install it?

**Comment by martin-netprofit** [comment]
yes, the installation worked

**Comment by bytehead** [comment]
I see now my failure: I've fixed the query for page siblings, not for news 🤦‍♂️ I'll update it accordingly.

**Comment by martin-netprofit** [comment]
no problem 🙂 thank very much for your help 😊

**Comment by bytehead** [comment]
@martin-netprofit Please update and check again :)

**Comment by martin-netprofit** [comment]
Perfect, now it works 👍
Thank you 🙂

**Comment by bytehead** [comment]
Nice. I will merge it and release a new version today.

**Comment by bytehead** [comment]
I've released [1.2.1](https://github.com/1up-lab/contao-sibling-navigation/releases/tag/1.2.1). Thanks for reporting and testing.
