### ISSUE TITLE
PHP 8.x compatibility

### ISSUE THREAD

**Issue by bytehead** [1up-lab/contao-sibling-navigation#18]
Raise PHP requirement to 7.4

**Comment by contaoacademy** [comment]
Is this extension compatible with Contao 4.13 and PHP 8.2?

**Comment by bytehead** [comment]
I don't know yet. But I can make it compatible 👍

**Comment by contaoacademy** [comment]
Maybe it would also be an idea to make one out of [this](https://github.com/inspiredminds/contao-sibling-navigation) and your extension ;-)

**Comment by bytehead** [comment]
I don't know the other one - what's the difference?

**Comment by contaoacademy** [comment]
I can check the differences for you. However, I don't have the time at the moment. I'll make a note of it and get back to you.

**Comment by contaoacademy** [comment]
I am using your extension with Contao 4.13 and PHP 8.2. Runs perfectly so far. The ticket can therefore be closed.

Unfortunately, I don't have time to continue pursuing the topic of merging with the other extension.

**Comment by bytehead** [comment]
Will update this extension to a bundle anyway with the next proper update.

**Comment by contaoacademy** [comment]
Now I have found a problem after all. When I activate the debug mode.
see: #20

**Comment by rorych** [comment]
@bytehead gibt es zum Update bereits News? Wir sind auch daran interessiert ;)

**Comment by bytehead** [comment]
@contaoacademy / @rorych gar nicht mehr auf meinem Radar gewesen. Schau mir das Issue asap noch  an.

**Comment by bytehead** [comment]
Closing in favor of #20

**Comment by bytehead** [comment]
@rorych Für Contao 5 gibts ein neues Issue.
