### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by rocchidavide** [1up-lab/contao-sibling-navigation#3]
I don't understand how to install it. In config.php paths are like 'Oneup\SiblingNavigation\ContentElement\Page\SiblingNavigation', in autoload.php they are like 'system/modules/sibling-navigation/templates/'

**Comment by bytehead** [comment]
This extension works with the contao composer plugin. [Read more here](https://c-c-a.org/ueber-composer), but it's german only.

**Comment by rocchidavide** [comment]
Thank you @bytehead

**Comment by Aybee** [comment]
If you like to install it manually you have to build this folder structure.
```
system
|  modules
|  |  oneup
|  |  |  config
|  |  |  contao-sibling-navigation
|  |  |  |  src
|  |  |  |  |  ContentElement
|  |  |  |  |  |  Event
|  |  |  |  |  |  News
|  |  |  |  |  |  Page
|  |  |  |  |  Helper
|  |  |  |  |  |  Event
|  |  |  |  |  |  News
|  |  |  |  |  |  Page
|  |  |  |  |  Module
|  |  |  |  |  |  Event
|  |  |  |  |  |  News
|  |  |  |  |  |  Page
|  |  sibling-navigation
|  |  |  config
|  |  |  dca
|  |  |  languages
|  |  |  |  de
|  |  |  |  en
|  |  |  templates

```
Don't forget to run the database update in extension manager after uploading all files.

Then in `BE > Developer tools` you have to run the "Autoload creator" on "oneup" to generate the autoload.php in system/modules/oneup/config/.
