### ISSUE TITLE
project still maintained?

### ISSUE THREAD

**Issue by fritzmg** [1up-lab/contao-sibling-navigation#9]
Is this project still maintained by 1up? Otherwise we might create a fork and continue development :)

**Comment by bytehead** [comment]
Yes, it is. Just had a break over the weekend 😀

**Comment by bytehead** [comment]
And there is some bugs to fix as well...

**Comment by fritzmg** [comment]
Ah ok... I wasn't sure whether this project will still be maintained, since the bug reports were from exactly a year ago. I ended up creating a new extension (with the same name, I hope you don't mind - if you do I can change it) since I needed a specific use case fairly quickly (in addition to the regular sibling navigation): https://github.com/inspiredminds/contao-sibling-navigation

It is created as a pure Contao 4 bundle and does not include the sibling navigation for pages, since the book navigation from the core already takes care of that (unless I am missing a specific feature that this extension offers in that regards).

**Comment by bytehead** [comment]
No worries, the bug reports are from @sheeep (maintainer as well).
We don't run into problems as long as you have your own vendor name 👍

**Comment by fritzmg** [comment]
Well as a matter of fact I did _not_ use a vendor name 😬 but the namespace is different from yours, so it's fine anyway. May be I'll add a vendor name though ;)

**Comment by bytehead** [comment]
I refer to `inspiredminds` in your `composer.json`: `"name": "inspiredminds/contao-sibling-navigation",` - all good! 😀
